### ISSUE TITLE
Add ESLint

### ISSUE THREAD

**Issue by johnpaulada** [johnpaulada/statestes#12]
Add ESLint with AirBnB style.

**Comment by murilodag** [comment]
Hello @johnpaulada, do you want it with a pre commit hook or just as a manual step?
Could I take this issue?

**Comment by johnpaulada** [comment]
Hey @murilodag I forgot to update this. It should be Standard style, not AirBnB style. Sorry 😢

**Comment by johnpaulada** [comment]
It's your call if you want to create a precommit hook for it. You can, if you want. If you don't, that's okay too. 😄 
Thank you!

**Comment by murilodag** [comment]
The 'standard' eslint config is a lot less restrictive than 'airbnb', so I think we are fine without it for now.

**Comment by johnpaulada** [comment]
Alright. Thanks! 😀
