### ISSUE TITLE
Add CDN version to README.md

### ISSUE THREAD

**Issue by johnpaulada** [johnpaulada/statestes#16]
> If you're new to the contribution process, check this out the [CONTRIBUTING.md](https://github.com/johnpaulada/statestes/blob/master/CONTRIBUTING.md) instructions.

Add a CDN version of importing this library to the *include using a CDN* section of the README.md file.
This means you have to get a CDN link for this library. I suggest using [jsDelivr](https://www.jsdelivr.com/).
Good luck and have fun! :tada:

**Comment by shindakun** [comment]
@johnpaulada wasn't aware jsDelivr was a thing. Hope the PR helps. :)
