### ISSUE TITLE
Add Pearson product-moment correlation coefficient

### ISSUE THREAD

**Issue by johnpaulada** [johnpaulada/statestes#24]
> If you're new to the contribution process, check this out the [CONTRIBUTING.md](https://github.com/johnpaulada/statestes/blob/master/CONTRIBUTING.md) instructions.

Create a function `pearsonR` that returns the **Pearson product-moment correlation coefficient** A.K.A. Pearson *r* from two arrays of data.

Create the function in the [*src/inference/inference.js*](https://github.com/johnpaulada/statestes/blob/master/src/inference/inference.js) file.

The function signature would be:
- `function pearsonR(leftData: [Int | Float], rightData: [Int | Float]) : Float`
- Int | Float -> Int | Float -> Float

How to calculate Pearson `r`:
- [Online Stat Book - Calculating Pearson r](http://onlinestatbook.com/2/describing_bivariate_data/calculation.html)
- [Pearson r calculation by hand](http://psc.dss.ucdavis.edu/sommerb/sommerdemo/correlation/hand/pearson_hand.htm)

Good luck and have fun! :smile: :fire: :100:

**Comment by murilodag** [comment]
Hello @johnpaulada, could I work on this one?

**Comment by johnpaulada** [comment]
Hey @murilodag ! Sure! Go ahead. If you have any questions, don't hesitate to ask. :smile:

**Comment by johnpaulada** [comment]
Just create a test at `src/inference/inference.test.js` to test the function you created. Thank you!
You can use `src/basic/basic.test.js` for reference. :smiley:
